"""Spec-kit-compatible Markdown templates.

Emits the file layout that github/spec-kit expects:

    <output-dir>/
    ├── memory/
    │   └── constitution.md
    └── specs/
        └── <feature-slug>/
            ├── spec.md
            ├── plan.md            (carries the OCTALUM 8-phase mapping)
            ├── research.md
            ├── data-model.md
            ├── quickstart.md
            ├── contracts/
            │   └── README.md
            └── tasks.md

All content is generated deterministically from the parsed `Project`
model — no LLM required. See `templates.py` for the legacy
"octalum-classic" output format kept for backward compatibility.
"""

from __future__ import annotations

from datetime import date

from .parser import Project
from .templates import OCTALUME_PHASES, _bullets

# --- constitution -----------------------------------------------------------

def render_constitution(p: Project) -> str:
    return f"""# Project Constitution

> Governing principles for **{p.title}**.
> Seeded by `octalum-bdtb` on {date.today().isoformat()}. Refine before locking.

These principles guide every downstream decision — `plan.md`, `tasks.md`,
and any code generated by spec-kit's `/speckit.implement` must respect them.

## I. Code Quality

- Code is read more than it is written. Optimise for the next reader.
- Every public function/endpoint has a docstring or schema entry.
- No commented-out code in `main`. Delete or branch.

## II. Testing Discipline

- A change without a test is a hypothesis, not a feature.
- Run the full suite locally before pushing; CI is a safety net, not a substitute.
- Tests describe behaviour, not implementation. Refactors should not break them.

## III. User Experience Consistency

- One pattern per concept. If two screens do "the same thing", they look the same.
- Errors are actionable: tell the user *what* went wrong and *what to do next*.
- Accessibility is not a Phase-5 task. WCAG 2.1 AA from day one.

## IV. Performance Awareness

- Measure before optimising; optimise the hot path, not the cold one.
- A page that takes > 1s to interact is broken.
- Database queries are explained (`EXPLAIN`) before merging.

## V. Security Posture

- Secrets never enter git. Use env vars + a secret manager.
- Dependencies are scanned in CI (Trivy / Snyk / `pip-audit`).
- Default-deny: every new endpoint is unauthenticated only by explicit choice.

## VI. Decision Hygiene

- Reversible decisions go fast. Irreversible decisions get a short ADR.
- Disagree and commit — but write down the disagreement.

---

_This constitution composes with the OCTALUM 8-phase SDLC framework and
github/spec-kit's `/speckit.constitution` command. Edit freely; this is
a starting point, not scripture._
"""


# --- spec ------------------------------------------------------------------

def render_spec(p: Project) -> str:
    features = _bullets(p.features[:20], empty="- _(parser detected no explicit features — fill in before /speckit.plan)_")
    goals = _bullets(p.goals, empty="- _(no explicit goals detected — fill in)_")
    constraints = _bullets(p.constraints, empty="- _(none detected)_")

    # Synthesise user stories from the top features.
    user_stories = []
    for i, f in enumerate(p.features[:5], 1):
        user_stories.append(
            f"- **US-{i:02d}** — As a user, I want to *{f[:120]}* so that the product delivers its core value."
        )
    if not user_stories:
        user_stories.append("- _(no user stories synthesisable — please add before /speckit.plan)_")

    return f"""# Feature Spec — {p.title}

> **What & why** — functional requirements only. No tech choices here;
> those live in `plan.md`. Generated by `octalum-bdtb` from a brain-dump
> on {date.today().isoformat()}.

## Summary

{p.summary or "_(no summary detected — please write a one-paragraph elevator pitch)_"}

## Primary domain

`{p.primary_domain}` (detected from keyword signals; override if wrong).

## Goals

{goals}

## User stories

{chr(10).join(user_stories)}

## Functional requirements

{features}

## Constraints

{constraints}

## Out of scope (v0.1)

- _List the things you explicitly will NOT build in the first slice._
- _A spec without an out-of-scope section silently scope-creeps._

## Acceptance criteria

- [ ] Every user story above has at least one end-to-end test.
- [ ] The "out of scope" list has been reviewed with stakeholders.
- [ ] Open questions in `research.md` are resolved or explicitly deferred.

---

_Next: `/speckit.plan` (or read the auto-generated `plan.md` already in this directory)._
"""


# --- plan ------------------------------------------------------------------

def render_plan(p: Project) -> str:
    stack = p.stack
    stack_rows = "\n".join(f"| {k} | {v} |" for k, v in stack.items())

    # OCTALUM 8-phase mapping inlined as a labelled section.
    phase_lines = []
    for name, desc in OCTALUME_PHASES:
        phase_lines.append(f"- **{name}** — {desc}")
    phases_md = "\n".join(phase_lines)

    return f"""# Implementation Plan — {p.title}

> **How** we will build what `spec.md` describes. Tech stack, architecture,
> and the cross-walk to the OCTALUM 8-phase SDLC framework.

## Tech stack (recommended)

| Concern | Choice |
|---------|--------|
{stack_rows}

_Rationale: optimised for time-to-first-deploy on `{p.primary_domain}` workloads.
Every entry is swappable — see `research.md` for the trade-offs._

## Architecture sketch

- **Entry point(s):** depends on domain — for `{p.primary_domain}`, see the tree below.
- **State / persistence:** see `data-model.md`.
- **External contracts:** see `contracts/` (API specs, event schemas).
- **Deployment target:** see the "hosting" / "ci" row in the stack table above.

## Suggested repo layout

See [`spec.md`](spec.md) "out of scope" before committing to this tree.
A starter layout for `{p.primary_domain}` projects:

```
{p.slug}/
├── src/
├── tests/
├── docs/
└── README.md
```

(For a fuller domain-specific tree, run `octalum-bdtb … --target octalum-classic`
and consult the generated `STRUCTURE.md`.)

## OCTALUM 8-phase mapping

> `octalum-bdtb` was born inside the OCTALUM family. The 8 phases below are
> preserved here so the OCTALUM methodology *composes* with spec-kit's
> `/speckit.tasks` and `/speckit.implement` commands — they don't conflict.

{phases_md}

`tasks.md` (in this same directory) is the spec-kit-native flattening of
phases 0–3; phases 4–7 are tracked at the OCTALUM workspace level. See
https://github.com/Harery/OCTALUME for the parent framework.

## Open questions blocking this plan

{_bullets(p.unknowns, empty="- _(none detected — that itself is suspicious; re-read the dump)_")}

---

_Next: refine with `/speckit.plan`, then generate `tasks.md` with `/speckit.tasks`._
"""


# --- research --------------------------------------------------------------

def render_research(p: Project) -> str:
    return f"""# Research — {p.title}

> Investigation log: what's known, what's rapidly changing, what needs a spike.
> Spec-kit treats this as a first-class artifact alongside `plan.md`.

## Stack decisions (from `plan.md`)

For each row in `plan.md`'s tech-stack table, document:

1. **Why this** (over the obvious alternatives).
2. **Lock-in score** (1 = trivial swap, 5 = year-long migration).
3. **Last reviewed** (date — re-evaluate quarterly).

| Component | Why | Lock-in | Alternatives | Last reviewed |
|-----------|-----|---------|--------------|---------------|
| _(fill from plan.md)_ |   |   |   | {date.today().isoformat()} |

## Open questions (extracted from brain-dump)

{_bullets(p.unknowns, empty="- _(none detected — surface 3+ before /speckit.plan)_")}

## Risks (extracted from brain-dump)

{_bullets(p.risks, empty="- _(no explicit risks detected — synthesise ≥3 before locking the plan)_")}

## Rapidly-changing areas to re-check

- LLM providers and pricing (refresh monthly if `--llm` is used)
- Frontend framework majors (Next.js, React)
- Cloud provider managed offerings (managed Postgres, managed auth)

## Spikes scheduled

- [ ] _(1-day spike on the highest-risk feature — see RISKS section)_

---

_Decisions captured here flow back into `plan.md` (Section: Tech stack)._
"""


# --- data-model -----------------------------------------------------------

def render_data_model(p: Project) -> str:
    domain = p.primary_domain
    starter = ""
    if domain == "saas":
        starter = """\
| Entity | Fields | Notes |
|--------|--------|-------|
| `User` | `id`, `email`, `created_at`, `tenant_id` | Auth via Clerk/Auth.js. |
| `Tenant` | `id`, `name`, `plan`, `created_at` | One tenant per paying account. |
| `Subscription` | `id`, `tenant_id`, `stripe_subscription_id`, `status` | Stripe-mirrored. |
"""
    elif domain == "iot":
        starter = """\
| Entity | Fields | Notes |
|--------|--------|-------|
| `Device` | `id`, `serial`, `firmware_version`, `last_seen_at` | Pi/ESP32. |
| `Reading` | `device_id`, `ts`, `metric`, `value` | TimescaleDB hypertable. |
| `Alert` | `id`, `device_id`, `ts`, `rule_id`, `acknowledged` | MQTT-driven. |
"""
    elif domain == "data":
        starter = """\
| Entity | Fields | Notes |
|--------|--------|-------|
| `Source` | `id`, `connector`, `last_synced_at` | Airbyte/Fivetran-ish. |
| `RawTable` | `source_id`, `schema`, `table`, `rows` | Lands in bronze layer. |
| `MartTable` | `name`, `dbt_model`, `refreshed_at` | dbt-managed. |
"""
    else:
        starter = """\
| Entity | Fields | Notes |
|--------|--------|-------|
| _(define your core entities here)_ | | |
"""

    return f"""# Data Model — {p.title}

> Schema and core entities. Populate before `/speckit.implement`.

## Entities

{starter}

## Relationships

- _(Draw the foreign-key graph. Mermaid `erDiagram` works in GitHub-rendered MD.)_

```mermaid
erDiagram
    USER ||--o{{ SESSION : has
```

## Migrations / change discipline

- Schema changes ship with an explicit migration file.
- Backwards-incompatible columns get a 2-deploy cycle (add → backfill → switch reads → drop).
- Every table has `created_at` and (where mutable) `updated_at`.

## PII / sensitive fields

- Mark every column carrying PII.
- Encryption-at-rest is the default; encryption-in-use only where threat-model demands it.
- Document retention policy per table.
"""


# --- quickstart -----------------------------------------------------------

def render_quickstart(p: Project) -> str:
    return f"""# Quickstart — {p.title}

> How a new contributor (or future you) gets the feature running locally
> in under 10 minutes.

## Prerequisites

- A recent runtime for the chosen stack (see `plan.md` → "Tech stack").
- Credentials for any third-party service flagged in `plan.md`.
- The repo cloned and the constitution (`../../memory/constitution.md`) skimmed.

## Setup

```bash
# 1. Clone
git clone <repo-url>
cd {p.slug}

# 2. Install
# (fill in based on stack — `npm i` / `pip install -e .` / `uv sync` / etc.)

# 3. Configure
cp .env.example .env
# edit .env with secrets
```

## Run locally

```bash
# (fill in — `npm run dev` / `python -m {p.slug.replace('-', '_')}` / etc.)
```

## Verify

- [ ] Health check returns 200.
- [ ] The first user story from `spec.md` works end-to-end.
- [ ] `pytest` (or the project's test runner) is green.

## Troubleshooting

- _(Common gotchas land here as the project matures.)_

---

_If a step here is wrong, fix it — out-of-date setup docs are a top-3 reason
contributors give up._
"""


# --- contracts -----------------------------------------------------------

def render_contracts_readme(p: Project) -> str:
    return f"""# Contracts — {p.title}

> External-facing contracts. Drop API specs, event schemas, and RPC
> definitions here. Spec-kit's `/speckit.implement` reads from this folder.

## Conventions

- One file per externally-visible surface.
- OpenAPI 3.1 → `api-spec.yaml` or `api-spec.json`.
- AsyncAPI 2.x → `events.yaml`.
- Proto / gRPC → `*.proto`.
- WebSocket / SignalR → `signalr-spec.md`.

## What lives here vs. inline

- **Lives here:** anything another team / system consumes.
- **Inline (in code):** internal-only DTOs, private RPCs.

## Starter

Replace this file with the appropriate spec for `{p.primary_domain}`:

- `saas` → `api-spec.yaml` (REST) + optional `events.yaml`
- `iot`  → MQTT topic catalog (`mqtt-topics.md`)
- `data` → `events.yaml` (Kafka/PubSub) + `dbt-contracts.yaml`
- `cli`  → `cli-contract.md` (flag/arg surface — yes, that's a contract too)
- `ml`   → `inference-api.yaml`
"""


# --- tasks ----------------------------------------------------------------

def render_tasks(p: Project) -> str:
    """Spec-kit-shaped flat task list with parallelism markers and deps."""
    lines = [
        f"# Tasks — {p.title}",
        "",
        "> Ordered, executable task list. `[P]` marks tasks that can run in",
        "> parallel with the previous one. Dependencies noted inline. Composes",
        "> with `/speckit.implement`.",
        "",
        "## Phase 0 — Discovery (US-* setup)",
        "",
        "- [ ] **T001** Validate the problem statement with 3+ potential users.",
        "- [ ] **T002** [P] Define success metrics (1 north-star + 2 supporting).",
        "- [ ] **T003** Resolve open questions in `research.md` (or explicitly defer).",
        "",
        "## Phase 1 — Architecture",
        "",
        "- [ ] **T010** Lock the tech stack in `plan.md` (after `/speckit.plan`).",
        "- [ ] **T011** [P] Draft `data-model.md` entities + relationships.",
        "- [ ] **T012** [P] Draft `contracts/` (API/event specs).",
        "",
        "## Phase 2 — Design & spike",
        "",
        "- [ ] **T020** Wireframe the primary user flow.",
        "- [ ] **T021** [P] Define the API contract end-to-end.",
        "- [ ] **T022** 1-day spike on the highest-risk feature (see `research.md`).",
        "",
        "## Phase 3 — Build (feature work)",
        "",
    ]
    if p.features:
        for i, f in enumerate(p.features[:8], start=30):
            tag = " [P]" if i > 30 else ""
            lines.append(f"- [ ] **T0{i:02d}**{tag} Implement: {f[:140]}")
    else:
        lines.append("- [ ] **T030** Implement vertical slice #1 (define the slice first).")
    lines += [
        "",
        "## Phase 4 — Integration & test",
        "",
        "- [ ] **T040** Contract tests for every entry in `contracts/`.",
        "- [ ] **T041** [P] End-to-end happy-path test for each US-* in `spec.md`.",
        "- [ ] **T042** [P] Dependency scan (Trivy / Snyk / pip-audit).",
        "",
        "## Phase 5 — Hardening",
        "",
        "- [ ] **T050** Threat-model (STRIDE).",
        "- [ ] **T051** [P] Confirm secrets never hit git (gitleaks in CI).",
        "- [ ] **T052** [P] Accessibility pass (WCAG 2.1 AA).",
        "",
        "## Phase 6 — Release",
        "",
        "- [ ] **T060** CI: build → test → deploy.",
        "- [ ] **T061** [P] Wire structured logs + traces.",
        "- [ ] **T062** Define rollback procedure.",
        "",
        "## Phase 7 — Operate",
        "",
        "- [ ] **T070** SLOs + error budget defined.",
        "- [ ] **T071** [P] Alerting wired (PagerDuty / Better Stack / equivalent).",
        "- [ ] **T072** Monthly roadmap review scheduled.",
        "",
        "---",
        "",
        "_Phase numbering follows the OCTALUM 8-phase SDLC framework so this file",
        "is readable as both a spec-kit `tasks.md` and an OCTALUM phase plan._",
        "",
    ]
    return "\n".join(lines)


# --- entry point -----------------------------------------------------------

def render_all_speckit(p: Project) -> dict[str, str]:
    """Return a {relative_path: content} map for the spec-kit layout."""
    slug = p.slug
    base = f"specs/{slug}"
    return {
        "memory/constitution.md": render_constitution(p),
        f"{base}/spec.md": render_spec(p),
        f"{base}/plan.md": render_plan(p),
        f"{base}/research.md": render_research(p),
        f"{base}/data-model.md": render_data_model(p),
        f"{base}/quickstart.md": render_quickstart(p),
        f"{base}/contracts/README.md": render_contracts_readme(p),
        f"{base}/tasks.md": render_tasks(p),
    }
