"""Markdown templates for the generated artifacts.

Pure string templates — no Jinja dependency, keeps install lean.
"""

from __future__ import annotations

from datetime import date

from .parser import Project

# --- File/folder tree suggestions by domain --------------------------------

TREES = {
    "saas": """\
{slug}/
├── apps/
│   ├── web/                # Next.js frontend
│   │   ├── app/
│   │   ├── components/
│   │   └── package.json
│   └── api/                # FastAPI backend
│       ├── routes/
│       ├── models/
│       └── pyproject.toml
├── packages/
│   └── shared/             # shared TS types
├── infra/                  # terraform / docker-compose
├── .github/workflows/
└── README.md
""",
    "cli": """\
{slug}/
├── src/{slug_underscore}/
│   ├── __init__.py
│   ├── cli.py              # Typer/Click entrypoint
│   └── core.py
├── tests/
│   └── test_cli.py
├── pyproject.toml
├── README.md
└── LICENSE
""",
    "iot": """\
{slug}/
├── firmware/               # ESP32 / Pi code
│   ├── src/
│   └── platformio.ini
├── ingest/                 # cloud-side service
│   └── main.py
├── dashboard/              # Grafana / Streamlit
├── infra/
│   └── mosquitto.conf
└── README.md
""",
    "data": """\
{slug}/
├── pipelines/              # Prefect/Airflow flows
├── transforms/             # dbt models
├── notebooks/
├── tests/
├── dbt_project.yml
└── README.md
""",
    "mobile": """\
{slug}/
├── app/                    # Expo / React Native
│   ├── screens/
│   └── components/
├── backend/                # Supabase functions
├── assets/
└── package.json
""",
    "ml": """\
{slug}/
├── data/                   # DVC-tracked
├── notebooks/
├── src/
│   ├── train.py
│   ├── eval.py
│   └── serve.py
├── configs/
└── pyproject.toml
""",
    "generic": """\
{slug}/
├── src/
├── tests/
├── docs/
├── README.md
└── LICENSE
""",
}


# OCTALUME's 8 phases (Phase-0 fed by this tool).
OCTALUME_PHASES = [
    ("Phase 0 — Discovery & Framing",
     "Refine the brain-dump into a problem statement, success metrics, scope."),
    ("Phase 1 — Requirements & Architecture",
     "Translate features into user stories; sketch C4 diagrams; pick stack."),
    ("Phase 2 — Design & Prototyping",
     "Wireframes / API contracts / data model; spike risky unknowns."),
    ("Phase 3 — Build & Implementation",
     "Iterative implementation in vertical slices."),
    ("Phase 4 — Integration & Testing",
     "End-to-end tests, contract tests, security scans."),
    ("Phase 5 — Hardening & Compliance",
     "Threat-model, secrets management, accessibility, perf."),
    ("Phase 6 — Deployment & Release",
     "CI/CD, blue-green or canary, observability wired."),
    ("Phase 7 — Operate & Iterate",
     "SLO dashboards, on-call, feedback loops, roadmap refresh."),
]


def _bullets(items: list[str], empty: str = "_(none detected — please review)_") -> str:
    if not items:
        return empty
    return "\n".join(f"- {x}" for x in items)


def render_structure(p: Project) -> str:
    tree = TREES.get(p.primary_domain, TREES["generic"]).format(
        slug=p.slug,
        slug_underscore=p.slug.replace("-", "_"),
    )
    return f"""# STRUCTURE — {p.title}

> Generated by **octalum-bdtb** on {date.today().isoformat()}.
> Primary domain detected: **{p.primary_domain}**.

## Proposed file/folder tree

```
{tree}
```

## Rationale

- The tree above is a **starting point** tuned for `{p.primary_domain}` projects.
- Keep `src/` and `tests/` siblings — most modern tooling expects this.
- `infra/` is included by default so you can codify environment from day one
  (matches OCTALUME Phase 5/6 expectations).
- Refactor freely; this is scaffolding, not scripture.

## Next step

Generate the scaffold:

```bash
octalum-bdtb "$(cat your_dump.md)" --output-dir ./plan --mode bootstrap
bash ./plan/BUILD_NOW.sh
```
"""


def render_stack(p: Project) -> str:
    stack = p.stack
    rows = "\n".join(f"| {k} | {v} |" for k, v in stack.items())
    return f"""# STACK — {p.title}

> Recommended stack for a **{p.primary_domain}** project.

| Concern | Recommendation |
|---------|----------------|
{rows}

## Rationale

- Optimised for **time-to-first-deploy**, not theoretical purity.
- All choices have strong OSS communities (matters when you hit Stack-Overflow-able problems at 2am).
- Every choice is **swappable**: nothing here is locking you in.
- Cybersecurity defaults assumed: managed auth, secrets in env vars / vault,
  HTTPS everywhere, dependency scanning in CI.

## Alternatives to consider

- If team has Rust/Go expertise, replace the API layer accordingly.
- For data-sensitive workloads, prefer self-hostable options (Supabase → Postgres, Clerk → Auth.js).
- If you anticipate strict compliance (HIPAA/SOC2), bias toward AWS/GCP managed services.
"""


def render_phases(p: Project) -> str:
    feature_bullets = _bullets(p.features[:20])
    goal_bullets = _bullets(p.goals)

    phase_sections = []
    for i, (name, desc) in enumerate(OCTALUME_PHASES):
        if i == 0:
            tasks = [
                "Validate problem statement with 3+ potential users",
                "Define success metric (1 north-star + 2 supporting)",
                "Decide build vs. buy for risky components",
            ]
            if p.unknowns:
                tasks.append("Resolve open questions (see RISKS.md)")
        elif i == 1:
            tasks = [
                "Pick concrete stack (see STACK.md)",
                "Sketch system context + container diagrams",
                "Write 5 highest-value user stories",
            ]
        elif i == 2:
            tasks = [
                "Wireframe primary flow",
                "Define API contract (OpenAPI / GraphQL schema)",
                "Spike highest-risk feature for 1 day",
            ]
        elif i == 3:
            tasks = [f"Implement: {f[:80]}" for f in (p.features[:5] or ["Vertical slice #1"])]
        elif i == 4:
            tasks = [
                "Add contract tests for public API",
                "End-to-end happy-path test",
                "Run dependency scan (e.g. Snyk, Trivy)",
            ]
        elif i == 5:
            tasks = [
                "Threat-model with STRIDE",
                "Confirm secrets never hit git (gitleaks in CI)",
                "Accessibility pass (WCAG 2.1 AA)",
            ]
        elif i == 6:
            tasks = [
                "GitHub Actions: build → test → deploy",
                "Wire structured logs + traces",
                "Define rollback procedure",
            ]
        else:
            tasks = [
                "Define SLOs and error budget",
                "Set up alerting (PagerDuty / Better Stack)",
                "Schedule monthly roadmap review",
            ]
        task_md = "\n".join(f"  - [ ] {t}" for t in tasks)
        phase_sections.append(f"### {name}\n\n*{desc}*\n\n{task_md}")

    phases_md = "\n\n".join(phase_sections)

    return f"""# PHASES — {p.title}

> Mapped onto **OCTALUME**'s 8-phase SDLC framework
> (see https://github.com/Harery/OCTALUME).

## Goals

{goal_bullets}

## Features detected

{feature_bullets}

---

{phases_md}
"""


def render_risks(p: Project) -> str:
    risks = _bullets(p.risks, empty="- _No explicit risks detected. Reviewer should add ≥3._")
    unknowns = _bullets(p.unknowns, empty="- _No open questions detected — that itself is suspicious. Re-read the dump._")
    constraints = _bullets(p.constraints, empty="- _None detected._")
    return f"""# RISKS — {p.title}

## Known risks

{risks}

## Open questions / unknowns

{unknowns}

## Constraints

{constraints}

## Decisions to make this week

- [ ] Confirm primary user persona
- [ ] Lock in tech stack (or commit to a 2-day spike)
- [ ] Define what's explicitly **out of scope** for v0.1
"""


def render_build_now(p: Project) -> str:
    slug = p.slug
    return f"""#!/usr/bin/env bash
# BUILD_NOW.sh — scaffold {p.title}
# Generated by octalum-bdtb. Review before running.

set -euo pipefail

PROJECT="{slug}"
echo "Bootstrapping $PROJECT ..."

mkdir -p "$PROJECT"/{{src,tests,docs}}
cd "$PROJECT"

cat > README.md <<'EOF'
# {p.title}

{p.summary or "TODO: 1-paragraph elevator pitch."}

## Status
Phase 0 — scaffolded by octalum-bdtb.
EOF

cat > .gitignore <<'EOF'
.venv/
__pycache__/
node_modules/
.env
.DS_Store
dist/
build/
EOF

echo "Done. Next: cd $PROJECT && git init && \\$EDITOR README.md"
"""


def render_all(p: Project) -> dict:
    return {
        "STRUCTURE.md": render_structure(p),
        "STACK.md": render_stack(p),
        "PHASES.md": render_phases(p),
        "RISKS.md": render_risks(p),
        "BUILD_NOW.sh": render_build_now(p),
    }
