#!/usr/bin/env bash
# BUILD_NOW.sh — scaffold dotsync — dotfile sync across machines without git
# Generated by brain-dump-to-build. Review before running.

set -euo pipefail

PROJECT="dotsync-dotfile-sync-across-machines-without-git"
echo "Bootstrapping $PROJECT ..."

mkdir -p "$PROJECT"/{src,tests,docs}
cd "$PROJECT"

cat > README.md <<'EOF'
# dotsync — dotfile sync across machines without git

I'm tired of dotfile repos. Every time I switch laptops I forget to push, or I commit a secret by accident. I want a CLI tool that syncs dotfiles via an encrypted blob stored on S3-compatible storage (R2, B2, whatever).

## Status
Phase 0 — scaffolded by brain-dump-to-build.
EOF

cat > .gitignore <<'EOF'
.venv/
__pycache__/
node_modules/
.env
.DS_Store
dist/
build/
EOF

echo "Done. Next: cd $PROJECT && git init && \$EDITOR README.md"
