#!/usr/bin/env bash
# BUILD_NOW.sh — scaffold SaaS for indie therapists
# Generated by octalum-bdtb. Review before running.

set -euo pipefail

PROJECT="saas-for-indie-therapists"
echo "Bootstrapping $PROJECT ..."

mkdir -p "$PROJECT"/{src,tests,docs}
cd "$PROJECT"

cat > README.md <<'EOF'
# SaaS for indie therapists

Ok so my sister is a therapist and she keeps complaining that all the practice-management SaaS out there is bloated, charges $80/mo, and is built for clinics not solo practitioners. I want to build something dead simple.

## Status
Phase 0 — scaffolded by octalum-bdtb.
EOF

cat > .gitignore <<'EOF'
.venv/
__pycache__/
node_modules/
.env
.DS_Store
dist/
build/
EOF

echo "Done. Next: cd $PROJECT && git init && \$EDITOR README.md"
