#!/usr/bin/env bash
# BUILD_NOW.sh — scaffold Greenhouse monitor for my dad's tomato obsession
# Generated by brain-dump-to-build. Review before running.

set -euo pipefail

PROJECT="greenhouse-monitor-for-my-dad-s-tomato-obsession"
echo "Bootstrapping $PROJECT ..."

mkdir -p "$PROJECT"/{src,tests,docs}
cd "$PROJECT"

cat > README.md <<'EOF'
# Greenhouse monitor for my dad's tomato obsession

My dad has a small backyard greenhouse and overwaters everything because he "feels it might be dry." I want a small IoT sensor array that just tells him, on his phone, whether to water today. No fancy automation — just data + a recommendation.

## Status
Phase 0 — scaffolded by brain-dump-to-build.
EOF

cat > .gitignore <<'EOF'
.venv/
__pycache__/
node_modules/
.env
.DS_Store
dist/
build/
EOF

echo "Done. Next: cd $PROJECT && git init && \$EDITOR README.md"
